#!/bin/bash
clear
echo "====================================="
echo "        MENU PREMIUM MULTIPLEXER     "
echo "====================================="
echo " 1. Tambah User SSH (addssh)"
echo " 2. Hapus User SSH (delssh)"
echo " 3. Lihat Daftar User (listssh)"
echo " x. Keluar Aplikasi (exit)"
echo "====================================="
read -p "Pilih menu [1-3 atau x]: " PILIH

case $PILIH in
    1) addssh ;;
    2) delssh ;;
    3) listssh ;;
    x|X) exit 0 ;;
    *) echo "Pilihan salah!"; sleep 1; menu ;;
esac
